version: "3"

services:
  # Grafana
  grafana:
    image: grafana/grafana:latest@sha256:ac461fb352abc50da10a51c7d02462e9c05488f11f53f14b3ad79a8145f638a0
    ports:
      - "3001:3000"
    volumes:
      - ../dist:/strava-datasource
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_FEATURE_TOGGLES_ENABLE=externalServiceAccounts
