version: "3"

services:
  # Grafana
  grafana:
    image: grafana/grafana:latest@sha256:70d9599b186ce287be0d2c5ba9a78acb2e86c1a68c9c41449454d0fc3eeb84e8
    ports:
      - "3001:3000"
    volumes:
      - ../dist:/strava-datasource
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_FEATURE_TOGGLES_ENABLE=externalServiceAccounts
